[package]
name = "compiler"
version = "0.1.0"
authors = ["Richard Rast <richard.rast@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytecode = { path="../bytecode" }

pest = "2.1"
pest_derive = "2.1"
